# Generated by Django 5.1.1 on 2024-09-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_loginmodel_id_alter_passwordresetmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='password',
            field=models.CharField(max_length=512),
        ),
    ]
