# Generated by Django 5.1.1 on 2024-09-23 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0006_alter_studentmodel_guardian_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('t_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('out_time', models.DateTimeField()),
                ('in_time', models.DateTimeField()),
                ('reason', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('S', 'Success'), ('F', 'Failed')], default='Pending', max_length=20)),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmodel')),
            ],
        ),
    ]
