# Generated by Django 5.1.1 on 2024-09-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transactionmodel',
            table='transaction',
        ),
    ]
