# Generated by Django 5.1.1 on 2024-09-25 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_studentmodel_guardian_name_and_more'),
        ('transaction', '0005_alter_transactionmodel_hostel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='actual_in_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='actual_out_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='qr_code_base_64',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='token',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='hostel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentmodel'),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('CI', 'Check_In'), ('CO', 'Check_Out'), ('S', 'Success'), ('F', 'Failed')], default='Pending', max_length=20),
        ),
    ]
