# Generated by Django 5.1.1 on 2024-09-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_transactionmodel_actual_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('CI', 'Check_In'), ('CO', 'Check_Out'), ('S', 'Success'), ('F', 'Failed'), ('E', 'Expired')], default='Pending', max_length=20),
        ),
    ]
