# Generated by Django 5.1.1 on 2024-09-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_transactionmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('CI', 'Check_In'), ('CO', 'Check_Out'), ('C', 'Completed'), ('E', 'Expired')], default='Pending', max_length=20),
        ),
    ]
