# Generated by Django 5.1.1 on 2024-10-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_alter_transactionmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='token_expire',
            field=models.DateTimeField(null=True),
        ),
    ]
