# Generated by Django 5.1.1 on 2024-09-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardenmodel',
            name='name',
            field=models.CharField(default='demo@gmail.com', max_length=30),
            preserve_default=False,
        ),
    ]
