# Generated by Django 5.1.1 on 2024-10-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0003_alter_wardenmodel_primary_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wardenmodel',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
