# Generated by Django 5.1.1 on 2024-09-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('mobile', models.BigIntegerField(null=True, unique=True)),
                ('profile', models.TextField()),
                ('parent_name', models.CharField(max_length=30)),
                ('parent_mobile', models.BigIntegerField(null=True, unique=True)),
                ('guardian_name', models.CharField(max_length=30)),
                ('guardian_mobile', models.BigIntegerField(null=True, unique=True)),
                ('home_addr', models.CharField(max_length=256)),
            ],
        ),
    ]
