# Generated by Django 5.1.1 on 2024-09-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='department',
            field=models.CharField(default='unkown', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
