# Generated by Django 5.1.1 on 2024-09-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentmodel_department'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentmodel',
            table='student',
        ),
    ]
