# Generated by Django 5.1.1 on 2024-09-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='department',
            field=models.CharField(max_length=20),
        ),
    ]
