# Generated by Django 5.1.1 on 2024-10-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_studentmodel_guardian_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='guardian_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
