# Generated by Django 5.1.1 on 2024-10-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_studentmodel_guardian_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='guardian_mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
