# Generated by Django 5.1.1 on 2024-09-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('dept_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('dept_name', models.CharField(max_length=30, unique=True)),
                ('staff_name', models.CharField(max_length=30)),
                ('staff_mobile', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
